name: Rust CI

on: 
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
  cargo_test:
    needs: cargo_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo test --verbose
  cargo_clippy:
    needs: [cargo_build, cargo_test]
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: clippy
          override: true
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features